// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8aLMwFmWrYIgDcDEVj5i9_BW8GvRqz0',
    appId: '1:809771467523:web:b14e8829d1105ec87a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    authDomain: 'tech-8ee17.firebaseapp.com',
    storageBucket: 'tech-8ee17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xRI6UK4NZRQocj7HCpkeo4MULubJbKM',
    appId: '1:809771467523:android:ad90a72bd2764c2d7a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKvlHDV-We8_eZB0iVb8ekzF_3z2LY-c',
    appId: '1:809771467523:ios:da8c47a4f9e254737a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.appspot.com',
    iosClientId: '809771467523-v87lo9rkmb6r9qp52fh7al9rp3dopg1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMKvlHDV-We8_eZB0iVb8ekzF_3z2LY-c',
    appId: '1:809771467523:ios:b11c2548503076b77a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.appspot.com',
    iosClientId: '809771467523-d5jpc0kn171fgpim97hhsd84ugbf2eco.apps.googleusercontent.com',
    iosBundleId: 'com.example.code.RunnerTests',
  );
}
